name: Scala build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Scala and SBT
      uses: olafurpg/setup-scala@v11
      with:
        java-version: adopt@1.11
    - name: Run tests
      run: sbt ";project gigahex-server; compile"

